### ISSUE TITLE
Windows Porting

### ISSUE THREAD

**Issue by Gusted** [Frewacom/Pywalfox-native#1]
https://pastebin.com/uDHAjGh2
AF_UNIX is for UNIX systems only

**Comment by Gusted** [comment]
`AttributeError: module 'socket' has no attribute 'AF_UNIX'`

**Comment by Frewacom** [comment]
I believe Windows 10 should [support](https://stackoverflow.com/questions/3872558/af-unix-in-windows) `AF_UNIX`, however, it would probably be better to just add a separate server/client for Windows that uses the UDP protocol and `AF_INET` socket type. 

The server would then bind to `localhost` and some port that we should define in `config.py`.

**Comment by Gusted** [comment]
![](https://i.imgur.com/vK6jcl3.png) I'm running 1909 and python 3.8.1 :/ So the support is no where to find...

**Comment by Gusted** [comment]
It's only avaible for C++ and Seems like Python didn't added support for it

Are you gonna make the server/client I'm not into sockets stuff and TCP/UDP protocols

**Comment by Frewacom** [comment]
Sure, I will add that feature. For now, I would recommend just disabling the socket server.

**Comment by Gusted** [comment]
Thank you a lot!

**Comment by Gusted** [comment]
![](https://i.imgur.com/4CFrFBW.jpg) Seems liked Got a good port to windows Extension didn't need any porting Only the socker server needs to be fixed

**Comment by Frewacom** [comment]
That's great! I will add the socket server and some OS specific settings later today probably.

**Comment by Gusted** [comment]
Thank you 2x I'm gonna port pywal to windows so it won't display the unix terminal colors and than a Nice darkreader Intergration

**Comment by Frewacom** [comment]
The socket server should now work with both Windows and Linux.

**Comment by Gusted** [comment]
Thank you! I will test it soon :sleeping:

**Comment by Frewacom** [comment]
I did not test it properly and there was some errors in `daemon.py`. I pushed a fix and it should be working again.

**Comment by Gusted** [comment]
Will test Tommrow* School gave me unexpected some more work to do Unannounced :/
